# Generated by Django 2.1.5 on 2019-01-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('contatoresposta', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('statusexcluido', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('motivocancelamento', models.CharField(choices=[('Padrão', 'Padrão'), ('OUTROS', 'OUTROS')], default='Padrão', max_length=10)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
